[build]
    base = "/"
    command = "make build"
    functions = "/functions"

[build.environment]
    GO_VERSION = "1.17.6"ret

[functions]
    directory = "src"

[functions.hello-cronny]
    schedule = "* * * * *"
ß